# Generated by Django 5.1.6 on 2025-02-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTM', '0002_automovel_remove_itemcarrinho_carrinho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacaousuario',
            name='automovel',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='automoveis_compatíveis',
        ),
        migrations.AddField(
            model_name='interacaousuario',
            name='codigo_fipe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Automovel',
        ),
        migrations.AddField(
            model_name='peca',
            name='automoveis_compatíveis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
